django-app/hinzu_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404

urlpatterns = [
    path('admin/', admin.site.urls),

    path('hinzu-django/', include('web_app.urls')),
]

handler404 = 'web_app.views.handler404'

django-app/web_app/urls.py
from django.urls import path

from . import views

app_name = 'web_app'

urlpatterns = [
    path('', views.upload_file, name='upload_file'),
    path('result/<str:domain>/', views.show_result, name='show_result'),
    path('api/addlike/', views.addlike, name='addlike'),
    path('api/fetch-image/<str:image_path_crypted>/', views.fetchImage, name='fetchImage'),
    path('favicon.ico/', views.favicon, name='favicon'),
    # 4 reactApp
    path('api-react/addlike/', views.RateImgView.as_view(), name='react_addlike'),
    path('api-react/upload/', views.UploadImgView.as_view(), name= 'upload_view'),
]

django-app/web_app/ml/models.py
import numpy as np

import torch
import torch.nn as nn
from torchvision import models
from torchvision import transforms

import PIL
import cv2

import os
MODELS_DIR = os.path.dirname(__file__)

class BeheadedDenseNet121(nn.Module):
    def __init__(self):
        super().__init__()
        network = models.densenet121(pretrained=True)
        self.model = nn.Sequential(network.features,nn.AvgPool2d(7,stride=1))

        normalize = transforms.Normalize(
           mean=[0.485, 0.456, 0.406],
           std=[0.229, 0.224, 0.225]
        )
        self.prepare = transforms.Compose([
           transforms.Resize(256),
           transforms.CenterCrop(224),
           transforms.ToTensor(),
           normalize
        ])

    def forward(self, x : PIL.Image):
        '''
            x - single image
        '''
        with torch.no_grad():
            e = self.model(self.prepare(x).unsqueeze(0)).squeeze(-1).squeeze(-1)  #  [B, C, 1, 1] -> [B, C]
            return e

    @staticmethod
    def output_embeddings_shape():
        return 1024


class PretrainedHeadOnTLLV1DenseNet121(nn.Module):
    # model pretrained for https://sites.google.com/view/totally-looks-like-dataset
    PRETRAINED_HEAD_ON_TLL_V1_DENSE_NET_121_FILE = 'PretrainedHeadOnTLLV1DenseNet121.weights'
    def __init__(self):
        super().__init__()
        self.head = torch.nn.Sequential(
            torch.nn.Linear(BeheadedDenseNet121.output_embeddings_shape(), 256),
            torch.nn.LeakyReLU(),
            torch.nn.Linear(256, 256),
            torch.nn.LayerNorm(256,elementwise_affine=False)
        )
        self.head.load_state_dict(torch.load(os.path.join(MODELS_DIR, self.PRETRAINED_HEAD_ON_TLL_V1_DENSE_NET_121_FILE)))
        self.model = nn.Sequential(BeheadedDenseNet121(), self.head)

    def forward(self, x : PIL.Image):
        '''
            x - single image
        '''
        with torch.no_grad():
            return self.model(x)

    @staticmethod
    def output_embeddings_shape():
        return 256


def upload_model(model_name : str):
    if model_name == 'BeheadedDenseNet121':
        return BeheadedDenseNet121()
    if model_name == 'PretrainedHeadOnTLL3LayersV1DenseNet121':
        return PretrainedHeadOnTLLV1DenseNet121()
    assert False, 'Set bad model name {}'.format(model_name)


def fix_PIL_img_shape(image: PIL.Image):
    image_arr = np.array(image)
    if len(image_arr.shape) == 2:
        image_arr = np.expand_dims(image_arr, -1)
    if image_arr.shape[-1] == 1:
        image = PIL.Image.fromarray(cv2.cvtColor(image_arr,cv2.COLOR_GRAY2RGB))
    elif image_arr.shape[-1] == 4:
        image = PIL.Image.fromarray(image_arr[:, :, :3])
    elif image_arr.shape[-1] != 3:
        assert False, "Bad image shape: {}".format(image_arr.shape)
    return image


def calc_embed(model : nn.Module, file : str):
    image = PIL.Image.open(file)
    image = fix_PIL_img_shape(image)
    e = model(image).squeeze(0)  # remove batch dim
    return np.array(e.detach())

django-app/web_app/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Embed(models.Model):
    path2similar = models.CharField(max_length=200)
    embeds_of_original = models.BinaryField()


class Rate(models.Model):
    embeds = models.ForeignKey(Embed, on_delete=models.CASCADE)
    rate = models.PositiveSmallIntegerField(blank=True, null=True)
    path2combined = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __str__(self):
        return self.path2combined.split('/')[-1]

django-app/web_app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, FileResponse, HttpResponse, Http404
from django.urls import reverse
import json
from django.conf import settings
from .models import Rate, Embed
from django.utils import timezone
from django.utils.datastructures import MultiValueDictKeyError
from django.views.decorators.http import require_POST

from werkzeug.utils import secure_filename
from .script import find_similar, preprocess, ImageTemplate
import os
import sys
from cryptography.fernet import Fernet
from PIL import Image, ExifTags
import cv2
from random import randint
from .ml.models import fix_PIL_img_shape
import time

from subprocess import Popen
import logging

from rest_framework.views import APIView
from rest_framework.parsers import MultiPartParser, FormParser, JSONParser
from rest_framework.response import Response
from rest_framework import status

logger = logging.getLogger(__name__)

ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

# set up logging
# logger = logging.getLogger('gunicorn.error')
# logger.handlers.extend(gunicorn_error_logger.handlers)
# logger.setLevel(logging.DEBUG)


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[-1].lower() in ALLOWED_EXTENSIONS

def save_orientationed_image(file, filepath):
    image=Image.open(file)
    try:
        for orientation in ExifTags.TAGS.keys():
            if ExifTags.TAGS[orientation]=='Orientation':
                break
        exif=dict(image._getexif().items())

        if exif[orientation] == 3:
            image=image.rotate(180, expand=True)
        elif exif[orientation] == 6:
            image=image.rotate(270, expand=True)
        elif exif[orientation] == 8:
            image=image.rotate(90, expand=True)
    except (AttributeError, KeyError, IndexError):
        if image.mode != 'RGB':
            image = fix_PIL_img_shape(image)
    finally:
        image.save(filepath)
        image.close()

def how2put_image_into_html(image_shape):
    yborder, xborder = 550, 300  # numbers from html accordingly
    kx = image_shape[1]/xborder
    if yborder >= image_shape[0]/kx:
        # expand with x (width)
        return 'width_mode'
    else:
        # expand with y (height)
        return 'heigh_mode'

def get_movie_name(path2img):
    path2img = path2img.split('/')
    path2img = path2img[-1].split('$')
    if len(path2img) == 1:
        print('Waring: {} is not a name for movie'.format(path2img[0]))
        return None
    return path2img[0].split('-')

def vconcat_resize_min(images:list, interpolation=cv2.INTER_CUBIC):  # this func is deprecated
    w_min = min(im.shape[1] for im in images)
    im_list_resize = [cv2.resize(im, (w_min, int(im.shape[0] * w_min / im.shape[1])), interpolation=interpolation)
                      for im in images]
    return cv2.vconcat(im_list_resize)

# def fetch_user_ip():
    # if request.environ.get('HTTP_X_FORWARDED_FOR') is None:
    #     app.logger.info('The main page was requested from ip : %s', request.environ['REMOTE_ADDR'])
    # else:
    #     app.logger.info('The main page was requested from ip %s', request.environ['HTTP_X_FORWARDED_FOR'])

def secure_filename_with_fix(filename):
    # https://stackoverflow.com/questions/21271465/saving-file-with-japanese-characters-in-python-3
    filename = secure_filename(filename)
    if '.' in filename:
        return filename
    return 'was_no_ascii_{}.'.format(randint(0, 100)) + filename

def dir_last_updated(folder):
    '''Trick for browser cache under static files'''
    path = os.path.join(settings.BASE_DIR, folder)
    return str(max(os.path.getmtime(os.path.join(root_path, f))
                   for root_path, dirs, files in os.walk(path)
                   for f in files))

################
# actual views #
################

class UploadImgView(APIView):
    parser_classes = (MultiPartParser, FormParser)

    def post(self, request, *args, **kwargs):
        print(request.COOKIES)

        if len(request.session.items()) != 0:
            request.session.flush()

        try:
            file = request.FILES['file']
        except MultiValueDictKeyError:
            return Response(status=status.HTTP_406_NOT_ACCEPTABLE)

        if file and allowed_file(file.name):
            filename = secure_filename_with_fix(file.name)
            filename = str(randint(0, 1e+18)) + '_' + filename  # secure filename more
            path2original = os.path.join(settings.UPLOAD_FOLDER, filename)
            save_orientationed_image(file, path2original)
            domain = request.POST.get('magic_mode') or 'movies'
            domain = domain.split(' ')[-1]
            path2similar, embeds = find_similar(settings, path2original, domain=domain)

            # save to model
            embed_model = Embed(path2similar=path2similar,
                                embeds_of_original=embeds)
            embed_model.save()

            # we found similar so lets cancate imgs via template
            # default template
            domain = 'movies'
            # create super name for new image
            filename_combined = '{domain}_ts_{time}_{randomNoriginal}'.format(domain=domain,
                                                                              time=time.strftime('%d.%m.%Y.%H.%M.%S'),
                                                                              randomNoriginal=path2original.split('/')[-1])
            path2combined = os.path.join(settings.REPORTS_FOLDER, filename_combined)

            # create new image
            try:
                img_template = ImageTemplate(path2original, path2similar)
            except NameError:
                logger.error('Exception with ImageTemplate, user is redirected to upload page.')
                return HttpResponseRedirect(reverse('web_app:upload_file'))
            if domain == 'movies':
                shape_4_html = img_template.to_movie(path2combined,
                                                    ' '.join(get_movie_name(path2similar)))
            elif domain == 'blurface':
                shape_4_html = img_template.to_blurface(path2combined)
            else:
                shape_4_html = img_template.to_vertical_concated(path2combined)

            request.session['path2combined'] = path2combined

            # crypt url
            f = Fernet(settings.FERNET_KEY)
            path2combined_crypted = f.encrypt(path2combined.encode())

            # delete original image & pop cookie
            p = Popen("rm %s" % path2original, shell=True)
            # request.session.pop('path2original')
            rate_model = Rate(embeds=get_object_or_404(Embed, pk=embed_model.id),#pk=request.session.get('id')),
                              path2combined=path2combined,
                              pub_date=timezone.now())
            rate_model.save()
            request.session['rate_id'] = rate_model.id
            # in above it was like in prev. version
            ########

            # ... in api cookie seems like no needed
            # btw may be we should use it for show result only once!?
            request.session['id'] = embed_model.id
            request.session['path2similar'] = path2similar
            request.session['path2original'] = path2original
            # return HttpResponseRedirect(reverse('web_app:show_result', args=(domain,)))
            variables_dict = {
                            'id' : embed_model.id,
                            'message': "Фото успешно загружено. Hinzu подобрал фильм!",
                            'domain' : domain,
                            'path2combined_crypted' : path2combined_crypted.decode(),
                            }
            if domain == 'movies':
                variables_dict['movie_name'] = ' '.join(get_movie_name(path2similar)).capitalize()
                variables_dict['movie_name_4search'] = '+'.join(get_movie_name(path2similar))
            return Response(
                variables_dict,
                status=status.HTTP_201_CREATED)
        else:
            return Response(status=status.HTTP_406_NOT_ACCEPTABLE)


class RateImgView(APIView):
    parser_classes = (MultiPartParser, FormParser)
    def post(self, request, *args, **kwargs):
        rate = request.POST.get('rate', None)
        if rate:
            message = 'Hinzu учтен Ваши пожелания!'
            rate_model = get_object_or_404(Rate, id=request.session.get('rate_id'))
            try:
                rate_model.rate = int(rate)
            except ValueError:
                rate_model.rate = None
            rate_model.save()
            variables_dict = {'message': message, 'rate':rate}
            return HttpResponse(json.dumps(variables_dict), content_type='application/json')
        return Response(status=status.HTTP_406_NOT_ACCEPTABLE)


def fetchImage(request, image_path_crypted):
    f = Fernet(settings.FERNET_KEY)
    try:
        image_path = f.decrypt(image_path_crypted.encode()).decode()
    except:
        raise Http404("Probably it is invalid file request!")
    try:
        response = FileResponse(open(image_path, 'rb'), as_attachment=False)
        return response
    except:
        raise Http404('file {} didnt find on server!'.format(image_path))

#########################
# hinzu on django views #
#########################

def upload_file(request):
    # fetch_user_ip()
    variables_dict = {'last_updated': dir_last_updated('web_app/static')}
    if len(request.session.items()) != 0:
        request.session.flush()
    if request.method == 'POST':
        file = request.FILES['file']
        if file and allowed_file(file.name):
            filename = secure_filename_with_fix(file.name)
            filename = str(randint(0, 1e+18)) + '_' + filename  # secure filename more
            path2original = os.path.join(settings.UPLOAD_FOLDER, filename)
            save_orientationed_image(file, path2original)

django-app/web_app/templates/web_app/base_template_page.html
<!DOCTYPE HTML>
{% load static %}
<html lang="ru">
<html>
  <head>
    <meta charset="utf-8">
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Hinzu, Make the Magic</title>
    {% endif %}
    {% if description %}
    <meta name="description" content="{{ description }}">
    {% else %}
    <meta name="description" content="Загружай свою фотографию, получай похожую фотографию знаменитостей, сцен из фильмов и даже мемов <*|*>">
    {% endif %}
    <link rel="shortcut icon" href="{% static 'web_app/images/favicon.ico' %}?u={{last_updated}}">
    <!--[if IE]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <![endif]-->
    <!-- <meta name="verify-admitad" content="fcc3e7c85b" /> -->

    <!-- viewport -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- user css -->
    <link rel="stylesheet" href="{% static 'web_app/css/style.css' %}?u={{last_updated}}">
    <!-- fonts for smiles -->
    <link rel="stylesheet" href="{% static 'web_app/css/all.css' %}?u={{last_updated}}">

    <style>
      @font-face {
        font-family: 'Girloub';
        src: url("{% static 'web_app/webfonts/Gilroy-Black.woff' %}");
        }
      @font-face {
        font-family: 'Gilroys';
        src: url("{% static 'web_app/webfonts/Gilroy-SemiBold.woff' %}");
        }
      @font-face {
        font-family: 'woff';
        src: url("{% static 'web_app/webfonts/fa-solid-900.woff' %}");
        }
      @font-face {
        font-family: 'woff2';
        src: url("{% static 'web_app/webfonts/fa-solid-900.woff2' %}");
        }
    </style>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-163928341-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-163928341-1');
    </script>

    <!-- Facebook Pixel Code -->
    <script>
      !function(f,b,e,v,n,t,s)
      {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
      n.callMethod.apply(n,arguments):n.queue.push(arguments)};
      if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
      n.queue=[];t=b.createElement(e);t.async=!0;
      t.src=v;s=b.getElementsByTagName(e)[0];
      s.parentNode.insertBefore(t,s)}(window, document,'script',
      'https://connect.facebook.net/en_US/fbevents.js');
      fbq('init', '651384928757656');
      fbq('track', 'PageView');
    </script>
    <noscript><img height="1" width="1" style="display:none"
      src="https://www.facebook.com/tr?id=651384928757656&ev=PageView&noscript=1"
    /></noscript>
    <!-- End Facebook Pixel Code -->

    <!-- for ajax scripts-->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

  </head>
  <body>
    {% block content %}{% endblock %}
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Popper -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous" ></script>
    <!-- for correct image preview-->
    <script type="text/javascript" src="{% static 'web_app/js/load-image.all.min.js' %}?u={{last_updated}}"></script>
    <script src="{% static 'web_app/js/load-image.js' %}?u={{last_updated}}"></script>

  </body>
</html>

django-app/web_app/templates/web_app/result.html
{% extends "web_app/base_template_page.html" %}

{% block content %}

  <header>
    <div class="container">
      <div class"row">
        <div class='col text-center'>
           <h1>Из какого ты
            {% if domain == 'memes' %}
            мема?
            {% elif domain == 'pinterest' %}
            мемного фильма (pinterest)?
            {% elif domain == 'movies' %}
            фильма?
            {% endif %}
           </h1>
           <p>Загружай свои фото в разных ситуациях</p>
        </div>
      </div>
    </div>
  </header>

  <section>

    <div class="container">
      <div class="row justify-content-center">
        <div class="col-12 col-md-4 text-center">

          <div class="card-group">
            <div class="card">
              <div class="thumbnail">
                <a href="{% url 'web_app:fetchImage' path2combined_crypted %}" target='_blank'>
                  {% if image_mode == 'width_mode' %}
                  <img src="{% url 'web_app:fetchImage' path2combined_crypted %}" alt="Lights" style="width: 100%;">
                  {% else %}
                  <img src="{% url 'web_app:fetchImage' path2combined_crypted %}" alt="Lights" style="height:550px">
                  {% endif %}
                </a>
              </div>
              <div class="card-block">
                <p></p>
                <h4 class="card-title">Хм-м... из какого же это {% if domain == 'memes' %}
                мема?
                {% elif domain == 'pinterest' %}
                мемного фильма (pinterest)?
                {% elif domain == 'movies' %}
                фильма?
                {% endif %}</h4>
                <p class="card-text">
                  {% if movie_name %}
                  Hinzu говорит, это из <a href="http://www.google.com/search?q=film+{{movie_name_4search}}" target="_blank">&laquo;{{ movie_name | title}}&raquo;</a>
                  {% else %}
                  Эту картинку подобрал для Вас HINZU
                  {% endif %}
                </p>
                <p></p>
              </div>
            </div>
          </div>
        </div>

      </div>

      <div class="row">
        <div class='col text-center top-buffer'>
          <button type="button" class="btn btn-success liker" rate="5" data-toggle="tooltip" data-placement="top" title="Hinzu подобрал то, что надо!"><i class="fas fa-heart"></i></button>
          <button type="button" class="btn btn-danger liker" rate="0" data-toggle="tooltip" data-placement="bottom" title="Что-то явно не то, - на пересдачу!"><i id=like1 class="fas fa-times"></i></button>
        </div>
      </div>

      <div id="m_success" class="d-none row justify-content-center top-buffer">
        <div class='col col-12 col-md-4 text-center'>
          <div class="alert alert-success alert-dismissible fade show">
          <strong>Yonked!</strong> Hinzu получил оценку и скоро дообучится! ;)
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          </div>
        </div>
      </div>

      <div id="m_danger" class="d-none row justify-content-center top-buffer">
        <div class='col col-12 col-md-4 text-center'>
          <div class="alert alert-danger alert-dismissible fade show">
          <strong>Not yonked!</strong> Что-то, не что-то );
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          </div>
        </div>
      </div>

      <div class="row">
        <div class='col text-center top-buffer'>
          <button onclick="location.href='{% url 'web_app:upload_file' %}';" class="btn btn-primary btn-lg btn-user">Попробовать еще (;</button>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-12 text-center top-buffer">
          <a class="scl-btn scl-crcl shadow fas fa-download" href="{% url 'web_app:fetchImage' path2combined_crypted %}" download></a>
          <a class="scl-btn scl-crcl shadow fab fa-telegram-plane" href="https://telegram.me/share/url?url=https%3A%2F%2Fhinzu.online%2Fapi%2Ffetch-image%2F{% url 'web_app:fetchImage' path2combined_crypted %}&text=Hinzu%2C%20Make%20the%20Magic&utm_source=share2" target="_blank"></a>
          <a  class="scl-btn scl-crcl shadow fab fa-facebook-f" href="https://www.facebook.com/sharer.php?src=sp&u=https%3A%2F%2Fhinzu.online%2Fapi%2Ffetch-image%2F{% url 'web_app:fetchImage' path2combined_crypted %}&title=Hinzu%2C%20Make%20the%20Magic&utm_source=share2" target="_blank"></a>
          <a  class="scl-btn scl-crcl shadow fab fa-twitter" href="https://twitter.com/intent/tweet?text=Hinzu%2C%20Make%20the%20Magic&url=https%3A%2F%2Fhinzu.online%2Fapi%2Ffetch-image%2F{% url 'web_app:fetchImage' path2combined_crypted %}&utm_source=share2" target="_blank"></a>
          <a  class="scl-btn scl-crcl shadow fab fa-linkedin-in" href="https://www.linkedin.com/shareArticle?mini=true&url=https%3A%2F%2Fhinzu.online%2Fapi%2Ffetch-image%2F{% url 'web_app:fetchImage' path2combined_crypted %}&title=Hinzu%2C%20Make%20the%20Magic&utm_source=share2" target="_blank"></a>
          <a  class="scl-btn scl-crcl shadow fab fa-whatsapp" href="https://api.whatsapp.com/send?text=Hinzu%2C%20Make%20the%20Magic%20https%3A%2F%2Fhinzu.online%2Fapi%2Ffetch-image%2F{% url 'web_app:fetchImage' path2combined_crypted %}&utm_source=share2" target="_blank"></a>
          <a  class="scl-btn scl-crcl shadow fab fa-reddit-alien" href="https://www.reddit.com/submit?url=https%3A%2F%2Fhinzu.online%2Fapi%2Ffetch-image%2F{% url 'web_app:fetchImage' path2combined_crypted %}&title=Hinzu%2C%20Make%20the%20Magic&utm_source=share2" target="_blank"></a>
          <a  class="scl-btn scl-crcl shadow fab fa-tumblr" href="https://www.tumblr.com/share/link?url=https%3A%2F%2Fhinzu.online%2Fapi%2Ffetch-image%2F{% url 'web_app:fetchImage' path2combined_crypted %}&utm_source=share2" target="_blank"></a>
        </div>
      </div>
    </div>
  </section>

  <footer id="footer" class="footer">
    <div class="container">
      <div class='row'>
        <div class='col-12 d-none d-sm-block text-center'>
          <h2>HINZU</h2>
          <p class=card-text style='margin:-30px; padding: 0;'><a href="mailto:kadochnikova@bk.ru?subject=Вопрос по Hinzu.online">kadochnikova@bk.ru</a><p>
        </div>
      </div>
      <div class='row'>
        <div class="col-12 d-block d-sm-none text-center">
          <h3>HINZU</h3>
          <p class=card-text style='margin:0; padding: 0;'><a href="mailto:kadochnikova@bk.ru?subject=Вопрос по Hinzu.online">kadochnikova@bk.ru</a><p>
        </div>
      </div>
    </div>
  </footer>

<script>
$('.liker').click(function(){
      $.ajax({
               type: "POST",
               url: "{% url 'web_app:addlike' %}",
               data: {'rate': $(this).attr('rate'), 'csrfmiddlewaretoken': '{{ csrf_token }}'},
               dataType: "json",
               success: function(response) {
                      // $("#m_success").html(response.message);
                      $("#m_success").removeClass("d-none");
                },
                error: function(rs, e) {
                       // alert(rs.responseText);
                       $("#m_danger").removeClass("d-none");
                }
          });
    })
</script>

<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>
{% endblock %}

django-app/web_app/templates/web_app/upload.html
{% extends "web_app/base_template_page.html" %}

{% block content %}
    <header>
      <div class="container">
        <div class"row">
          <div class="col text-center">
               <h1>Из какого ты фильма?</h1>
               <p>Загружай свои фото в разных ситуациях</p>
          </div>
        </div>
      </div>
    </header>

    <section>
      <div class="container">
        <div class"row">
          <div class='col text-center'>
            <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
            <main class="main_full">
                <form action="{% url 'web_app:upload_file' %}" method=post enctype=multipart/form-data>
                  {% csrf_token %}
                  <div class="panel">
                    <div class="button_outer">
                      <div class="btn_upload btn-user">
                        <input type="file" id="upload_file" name="file" onchange="readFile(this.value)">
                        Выбрать Фото
                      </div>
                      <div class="processing_bar"></div>
                      <div class="success_box"></div>
                    </div>
                  </div>
                  <div class="error_msg"></div>
                  <div class="uploaded_file_view" id="uploaded_view">
                    <img id="result" class="result" />
                    <span class="file_remove">X</span>
                  </div>

                  <div id="push4magic" class="btn-group d-none" >
                    <button type="button submit" class="btn btn-primary btn-lg btn-user" >Create baraban   </button>
                  </div>

                </form>
            </main>
          </div>
        </div>
      </div>
    </section>

    <footer id="footer" class="footer">
      <div class="container">
        <div class='row'>
          <div class='col-12 d-none d-sm-block text-center'>
            <h2>HINZU</h2>
            <p class=card-text style='margin:-30px; padding: 0;'><a href="mailto:kadochnikova@bk.ru?subject=Вопрос по Hinzu.online">kadochnikova@bk.ru</a><p>
          </div>
        </div>
        <div class='row'>
          <div class="col-12 d-block d-sm-none text-center">
            <h3>HINZU</h3>
            <p class=card-text style='margin:0; padding: 0;'><a href="mailto:kadochnikova@bk.ru?subject=Вопрос по Hinzu.online">kadochnikova@bk.ru</a><p>
          </div>
        </div>
      </div>
    </footer>
{% endblock %}